export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const UPDATE_PAYMENT_INFO = 'UPDATE_PAYMENT_INFO';
export const UPDATE_ADDRESS_INFO = 'UPDATE_ADDRESS_INFO';