export const FETCH_TO_CART = 'FETCH_TO_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const UPDATE_CART_ITEM_QUANTITY = "UPDATE_CART_ITEM_QUANTITY";
export const CLEAR_CART = "CLEAR_CART";
export const SET_CHECK_STATUS = "SET_CHECK_STATUS";
export const UPDATE_HAS_COUPON_CODE = "UPDATE_HAS_COUPON_CODE";